---
- name: Install nginx and  apache upload
  hosts: all
  become: yes

  vars:
          source_file: ./index.html
          source_file1: ./index1.html
          destin_file: /var/www/html

  tasks:
          - name: Check ver Linux
            debug: 
              var: ansible_nodename

          - name: Install Nginx server for db1
            apt: name=nginx state=present
            when: ansible_nodename == "ip-172-31-26-11"

          - name: Install Apache for db2
            yum: name=apache2 state=present
            when: ansible_nodename == "ip-172-31-25-161"

          - name: Copy html
            copy: src={{ source_file }} dest={{ destin_file }}
            when: ansible_nodename == "ip-172-31-26-11"
            notify: Restart nginx

          - name: Copy html Apache
            copy: src={{ source_file2 }} dest={{ destin_file }}
            when: ansible_nodename == "ip-172-31-25-161"
            notufy: Restart Apache

          - name: Start nginx
            service: name=nginx state=started enabled=yes
            when: ansible_nodename == "ip-172-31-26-11"

          - name: Start nginx for RedHat
            service: name=apache2 state=started enabled=yes
            when: ansible_nodename == "ip-172-31-25-161"

  handlers:
          - name: Restart nginx
            service: name=nginx state=restarted
            
          - name: Restart Apache
            service: name=apache2 state=restarted
            

...
