# This is a basic workflow to help you get started with Actions

name: First_actions

on:
  push:
    branches: master 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: View dir
      run: ls -ll
  build:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, worl!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
     
